### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by irvnriir** [MomsFriendlyDevCo/triple-folds#3]

**Comment by hash-bang** [comment]
I'm afraid I've not used Atom for some time.

Can you provide a bit more detail on what you are seeing. Are you getting an error or something?

**Comment by irvnriir** [comment]
@hash-bang don't getting anything just the action ,inside the marked region doesn't work

**Comment by hash-bang** [comment]
Sorry but we don't really use Atom any more at this end.

I'll mark the project as depreciated.
